name: White Paper
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >

master_repo: false
url: "http://joanie.cappetta.github.io/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           joanie
  avatar:         
  email:          "joanie.cappetta@gmail.com"
 
# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
